version: '3'
 
services:
  web_admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chungkhoangso1-web_admin
    restart: always
    ports:
      - 8080:80
    volumes:
      - ../../web_admin/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  