version: '3'
 
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: chungkhoangso1vn
      MYSQL_DATABASE: app_db
      MYSQL_USER: api_dev
      MYSQL_PASSWORD: chungkhoangso1vn
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: sks1-api
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=api_dev
      - DB_PASSWORD=chungkhoangso1vn
      - DB_DATABASE=app_db
      - PORT=3000
      - UV_THREADPOOL_SIZE= 20
    expose:
      - 3000
  
  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../web_admin/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 99999K
    restart: always
    expose:
      - 80
  
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - 9000
      - 9001
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: chungkhoanso1vn
      MINIO_BROWSER_REDIRECT_URL: http://minio.chungkhoanso1.vn
      MINIO_SERVER_URL: http://storage.chungkhoanso1.vn
    command: server --console-address ":9001" /data
