version: '3'
 
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: chungkhoangso1vn
      MYSQL_DATABASE: app_db
      MYSQL_USER: api_dev
      MYSQL_PASSWORD: chungkhoangso1vn
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 99999K
    restart: always
    ports:
      - 8081:80
